name: interproscan_run
description: Run Interproscan
keywords:
  - fasta
tools:
  - interproscan:
      description: |
        InterPro is a database which integrates together predictive information about proteins' function
      homepage: https://interproscan-docs.readthedocs.io
      licence: ["Apache License 2.0"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA file
      pattern: "*.{fa,fasta}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - out_interpro:
      type: file
      description: InterPro output file
      pattern: "out_interpro_*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@toniher"
